export const PokemonTypes = [
  {
    name: "normal",
    label: "Normal",
    color: "#919AA2",
    backgroundColor: "#F1F2F3",
  },
  {
    name: "fighting",
    label: "Lutador",
    color: "#CE416B",
    backgroundColor: "#F8E9EE",
  },
  {
    name: "flying",
    label: "Voador",
    color: "#89AAE3",
    backgroundColor: "#F1F4FA",
  },
  {
    name: "poison",
    label: "Venenoso",
    color: "#B567CE",
    backgroundColor: "#F5EDF8",
  },
  {
    name: "ground",
    label: "Terrestre",
    color: "#D97845",
    backgroundColor: "#F9EFEA",
  },
  {
    name: "rock",
    label: "Pedra",
    color: "#C5B78C",
    backgroundColor: "#F7F5F1",
  },
  {
    name: "bug",
    label: "Inseto",
    color: "#91C12F",
    backgroundColor: "#F1F6E8",
  },
  {
    name: "ghost",
    label: "Fantasma",
    color: "#5269AD",
    backgroundColor: "#EBEDF4",
  },
  {
    name: "steel",
    label: "Metal",
    color: "#5A8EA2",
    backgroundColor: "#ECF1F3",
  },
  {
    name: "fire",
    label: "Fogo",
    color: "#FF9D55",
    backgroundColor: "#FCF3EB",
  },
  {
    name: "water",
    label: "Água",
    color: "#5090D6",
    backgroundColor: "#EBF1F8",
  },
  {
    name: "grass",
    label: "Grama",
    color: "#63BC5A",
    backgroundColor: "#EDF6EC",
  },
  {
    name: "electric",
    label: "Eletrico",
    color: "#F4D23C",
    backgroundColor: "#FBF8E9",
  },
  {
    name: "psychic",
    label: "Psíquico",
    color: "#FCEEEF",
    backgroundColor: "#FA7179",
  },
  {
    name: "ice",
    label: "Gelo",
    color: "#73CEC0",
    backgroundColor: "#F1FBF9",
  },
  {
    name: "dragon",
    label: "Dragão",
    color: "#0B6DC3",
    backgroundColor: "#E4EEF6",
  },
  {
    name: "dark",
    label: "Noturno",
    color: "#5A5465",
    backgroundColor: "#ECEBED",
  },
  {
    name: "fairy",
    label: "Fada",
    color: "#EC8FE6",
    backgroundColor: "#FBF1FA",
  },
  {
    name: "stellar",
    label: "Estrelar",
    color: "#4A4A4A",
    backgroundColor: "#E8E8E8",
  },
  {
    name: "unknown",
    label: "Desconhecido",
    color: "#919AA2",
    backgroundColor: "#F1F2F3",
  },
];
